### ISSUE TITLE
Nome do módulo em exemplos

### ISSUE THREAD

**Issue by raphael-abreu** [manoelcampos/NCLuaHTTP#1]
Olá Manoel, no ultimo commit alterou o nome do módulo para "ncluahttp" porém as chamadas nos exemplos continuam usando o nome antigo "http"

exemplo01.lua, linha 24: `http.getFile("http://manoelcampos.com/arquivos/arquivo.txt", callback)`

Abraços,

**Comment by manoelcampos** [comment]
Olá @raphael-abreu,

Obrigado. Já corrigi os exemplos mas não sei se o módulo ainda funciona na atual implementação do Ginga NCL. Já não trabalho na área de TVD. Se você puder testar e me dar um feedback, agradeço.

**Comment by raphael-abreu** [comment]
Olá Manoel, testei o módulo na máquina virtual Ginga. Em meus testes ele funcionou para todas as requisições GET. 
Para as POST ele funciona ao enviar strings, mas não funcionou no caso de envio de arquivo.   
Abraços,

**Comment by manoelcampos** [comment]
Olá @raphael-abreu,

Obrigado. Asim que eu puder verifico.
