### ISSUE TITLE
request https

### ISSUE THREAD

**Issue by JulienLeal** [manoelcampos/NCLuaHTTP#3]
Fala manoel, beleza?

Como eu faria um request https com o seu módulo ?

Abs.

**Comment by manoelcampos** [comment]
Olá Julien,
O NCLuaHTTP não tem como fazer acesso a páginas HTTPS pois não há algoritmos criptográficos disponíveis para NCLua no Ginga NCL.

Existem um projeto chamado [LuaTV](http://gingacdn.lavid.ufpb.br/libs/luatv-project) que aparentemente possui coisas relacionadas à segurança, mas eu já não atuava mais na área de TVD quando o projeto foi lançado. Assim, não sei o que há disponível e funcionando.

Mesmo que o LuaTV possua tais recursos, os Set-Top Boxes e TVs com Ginga existentes no mercado não terão tal funcionalidade. Assim, se realmente precisa de HTTPS, deve optar pelo JavaDTV.
